name: ESPresense Companion
version: 0.4.0
slug: espresense-companion
description: Home Assistant Add-on for precise BLE device tracking and ESPresense node management on a home floorplan
url: https://espresense.com/companion
image: espresense/espresense-companion
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
map:
  - config:rw
ingress: true
ingress_stream: true
ingress_port: 8267
panel_icon: mdi:alpha-e-circle
panel_title: ESPresense
homeassistant_api: true
services:
  - mqtt:want

