name: ESPresense Companion
version: 0.1.4
slug: companion
description: ESPresense Companion Add On
url: https://espresense.com/
image: espresense/espresense-companion
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
map:
  - config:rw
ingress: true
ingress_port: 8267
panel_icon: mdi:alpha-e-circle
panel_title: ESPresense
services:
  - mqtt:want
